name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Install PyInstaller
        pip install -r requirements.txt  # Install other dependencies

    - name: Build application
      run: |
        pyinstaller --onefile splitter.py  # Replace splitter.py with your main file

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: |
          dist/splitter  # Adjust the path if necessary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}